### ISSUE TITLE
Versioning of data instance values

### ISSUE THREAD

**Issue by gedw99** [ipfs/go-ds-badger#21]
Badger is amazing in that it supports versions of data.

This is very useful for eventually consistent systems and opens the door to consensus happening even when the network partitions and then reforms.

So I am wondering if versioning is going to be part of the IPFS data store interface ?

Just to put some more use cases here, when you have a versioning data store it makes it much much easier to do CRDT style systems because you can design either OT or State based sync systems.

Dgraph rely on badger being versioning in order to do eventual consistency of their dgraph cluster for example.

**Comment by Stebalien** [comment]
We may end up taking advantage of it but otherwise no. For us, the datastore is just a place where we put data (basically, a filesystem). We define the interface so that we can *internally* swap out different datastores. However, it's a not a part of the *external* ipfs interface/protocol.

As for versioning in IPFS (or IPLD if you're interested in things like CRDTs), that's usually best done by adding a "previous version" pointer to the root of your state tree pointing to the previous state tree.

FYI, you'll likely be interested in https://github.com/ipfs/research-CRDT (and https://github.com/ipfs/research-CRDT#crdt-libraries-using-ipfs).

(closing to keep open issues from piling up, feel free to ask follow up questions)

**Comment by gedw99** [comment]
@Stebalien 

thanks for the thorough response....

I know about the various ipfs-crdt initiatives. All of them are coded in JS and there are others too and its actually the exact opposite of what i want to do.

My use case is simple to describe, but hard to build:
1. stand up many IPFS nodes, and allow edits on any of them for the same instance of data.
2. support network partitions and reforming.

Its basically apeer to peer datbase / content store.  Because so many SPA web apps are built with a Webview, you could just compile the Webview (and your very very standard web app) with a IPFS node running on the Desktop or node), with a simple JSON interface locally between them.
IN this way the Front end developer does not have to concern themselves with CRDT and all that. Its all encapsulated in the IPFS node compiled and running on the device. Doing this architecturally is pretty well known stuff now thanks for gomobile, etc.. So no road blocks there.. Anyway, thats what i think about it but i am sure others have other use cases too.

So getting back to the point,  CRDT Javascript libs are pointless for my approach 

---

Regarding the IPLD and adding a "previous record", are  there any links on that ? i would love to dig into that deeper and see what workflows and test harnesses i can built to try out sync workflows.

**Comment by Stebalien** [comment]
In go? Not that I know of. While the js libs may not help you directly, I recommend you look at *how* they use IPLD.

For a quick example using the command line and IPFS:

```bash
V1="$(printf '{"foo": "bar"}' | ipfs dag put)"
V2=$(printf '{"parent": {"/": "%s"}, "foo": "bar2"}' "$V1" | ipfs dag put)
echo "Version 1: $V1"
ipfs dag get $V1
echo "Version 2: $V2"
ipfs dag get $V2
```

Note: The `{"/": ...}` syntax is our way of representing "links" in json.

**Comment by gedw99** [comment]
That looks very concise. Will play around with it to learn. thanks again
for your help.
